
#!/bin/bash

sudo amm enable access_compat_module
sudo amm enable alias_module
sudo amm enable auth_basic_module
sudo amm enable authn_core_module
sudo amm enable authn_file_module
sudo amm enable authn_socache_module
sudo amm enable authz_core_module
sudo amm enable authz_groupfile_module
sudo amm enable authz_host_module
sudo amm enable authz_user_module
sudo amm enable autoindex_module
sudo amm enable dir_module
sudo amm enable env_module
sudo amm enable filter_module
sudo amm enable headers_module
sudo amm enable hfs_apple_module
sudo amm enable http2_module
sudo amm enable log_config_module
sudo amm enable mime_module
sudo amm enable negotiation_module
sudo amm enable php7_module
sudo amm enable proxy_ajp_module
sudo amm enable proxy_connect_module
sudo amm enable proxy_fcgi_module
sudo amm enable proxy_ftp_module
sudo amm enable proxy_http_module
sudo amm enable proxy_module
sudo amm enable proxy_scgi_module
sudo amm enable reqtimeout_module
sudo amm enable rewrite_module
sudo amm enable setenvif_module
sudo amm enable slotmem_shm_module
sudo amm enable socache_shmcb_module
sudo amm enable ssl_module
sudo amm enable unixd_module
sudo amm enable version_module
sudo amm enable watchdog_module
